
# General info used by Actuator in the /info endpoint.
info:
  build:
    # Values from pom.xml.
    version: @project.version@
    artifactId: @project.artifactId@
    groupId: @project.groupId@
    name: bootbase
    description: ${info.build.name} is a bootstrap project for Spring Boot. # Example of placeholder in properties.

# Server.
server:
  port: 8001 # Use 0 for a free random port.

spring:
  output:
    ansi:
      enabled: ALWAYS # Enable color logs.

# Logging configuration.
logging:
  level:
    es.apinazo: DEBUG # Level by package.
    root: INFO # Global level for anything that doesn't match the level by package.

# Actuator.
# https://docs.spring.io/spring-boot/docs/2.0.0.BUILD-SNAPSHOT/actuator-api//html/#overview
# IMP: If this configuration is in the bootstrap file it will be ignored.
# The list of all enabled endpoints will show in the app log when it starts.
management:

  endpoints:
    web:
      base-path: /actuator # URL prefix to all endpoints. "/actuator" by default.
      enabled-by-default: true # By default is true but in order to work they must be both enabled and exposed.
      exposure:
        include: "*" # Expose all endpoints. By default only health and info are exposed.
#        exclude: shutdown, beans # Don't expose this endpoints.

  # It's possible to manage all endpoints one by one.
  endpoint:

    demo:
      enabled: true # Enables custom endpoint /actuator/demo.

    health:
      show-details: always # Values: always, never, when-authorized - by Spring Security.

# Demo configurations.
configurations:
  first:
    enabled: true
  second:
    # If this is enabled then ConfConditionalOnSecondConf will be enabled.
    enabled: false

# Example configuration for PropsConfiguration class.
props:
  name: A name
  enabled: true
  listOfThings: one, two, three
  anotherListOfThings:
    - one
    - two
    - three
  firstInnerConf:
    key: The key
    value: The value
  secondInnerConf:
    key: The key
    value: The value
  innerConfArray:
    - key: one
      value: one
    - key: two
      value: two

