
# General info used by Actuator in the /info endpoint.
info:
  build:
    # Values from pom.xml.
    version: @project.version@
    artifactId: @project.artifactId@
    groupId: @project.groupId@
    name: bootbase
    description: ${info.build.name} is a bootstrap project for Spring Boot. # Example of placeholder in properties.

# Server.
server:
  port: 8001 # Use 0 for a free random port.
  compression:
    enabled: true # Enable compression for html, xml, css and plain text.
    min-response-size: 1024 # For files greater or equal to 1024 bytes.

spring:

  # Logs.
  output:
    ansi:
      enabled: ALWAYS # Enable color logs.

  # JPA.
  jpa:
    hibernate:
      show-sql: false # Hide Hibernate logs but if log level is DEBUG this will be ignored.
      format-sql: true # Beautify ugly Hibernate queries.
      ddl-auto: update # none, update, create, create-drop.

  # Datasource.
  datasource:
    generate-unique-name: true # To avoid tests to reuse the same DB. There will be one DB for each context.
    url: jdbc:p6spy:mysql://localhost/bootbase
    username: bootbase
    password: bootbase
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      test-on-borrow: true # Tests a connection from the pool before using it.
      validation-query: SELECT 1 # Query used to validate the connection.

# Logging configuration.
logging:
  level:
    es.apinazo: TRACE # Level by package.
    org.springframework.aop.interceptor: TRACE
    com.sun.proxy: TRACE # For proxies such as dynamic repositories.
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    root: INFO # Global level for anything that doesn't match the level by package.

# Actuator.
# https://docs.spring.io/spring-boot/docs/2.0.0.BUILD-SNAPSHOT/actuator-api//html/#overview
# IMP: If this configuration is in the bootstrap file it will be ignored.
# The list of all enabled endpoints will show in the app log when it starts.
management:

  endpoints:
    web:
      base-path: /actuator # URL prefix to all endpoints. "/actuator" by default.
      enabled-by-default: true # By default is true but in order to work they must be both enabled and exposed.
      exposure:
        include: "*" # Expose all endpoints. By default only health and info are exposed.
#        exclude: shutdown, beans # Don't expose this endpoints.

  # It's possible to manage all endpoints one by one.
  endpoint:

    demo:
      enabled: true # Enables custom endpoint /actuator/demo.

    health:
      show-details: always # Values: always, never, when-authorized - by Spring Security.

  metrics:
    web:
      server:
        # Enable global measurement of all in the app requests. Alternatively this could be set to false
        # and then each individual @Controller to measure can be annotated with @Timed.
        # Statistics will be available at the URI:
        #     /actuator/metrics/http.server.requests?tag=uri:<URL encoded endpoint URI>
        # Example for /persons/{id}:
        #     http://localhost:8001/actuator/metrics/http.server.requests?tag=uri:%2Fpersons%2F%7Bid%7D
        auto-time-requests: true


# Demo configurations.
configurations:
  first:
    enabled: true
  second:
    # If this is enabled then ConfConditionalOnSecondConf will be enabled.
    enabled: false

# Example configuration for PropsConfiguration class.
props:
  name: A name
  enabled: true
  listOfThings: one, two, three
  anotherListOfThings:
    - one
    - two
    - three
  firstInnerConf:
    key: The key
    value: The value
  secondInnerConf:
    key: The key
    value: The value
  innerConfArray:
    - key: one
      value: one
    - key: two
      value: two

# Custom audit configuration.
bootbase:
  profiling:
    api:
      enabled: true
    service:
      enabled: true
    repository:
      enabled: true
    requests:
      enabled: true
