# Configuration applied only when 'pre' profile is active.
#
# Here are the environment dependant configurations.

# Server.
server:
  port: 8001 # Use 0 for a free random port.

# Logging configuration.
logging:
  level:
    es.apinazo: DEBUG
    root: INFO
