# Configuration applied only when 'pro' profile is active.
#
# Here are the environment dependant configurations.

# Server.
server:
  port: 8001 # Use 0 for a free random port.

# Logging configuration.
logging:
  level:
    root: WARN